### ISSUE TITLE
Add integration tests for revocation load and distribution.

### ISSUE THREAD

**Issue by gargravarr** [zalando/planb-revocation#103]
Test the resilience of the Revocation Service. Here's a general description of the test case:
1. Load _n_ revocations in Cassandra
2. Get revocations
3. Assert that the number of retrieved revocations = _n_

Implement this in the following scenarios:
### Scenario 1: Load test

**Test several revocation loads**
- _n_ varies between 1 and 13.000.000 - ask @jeffsantarossa why - and should grow exponentially;
- `revoked_at` doesn't matter here (Use defaults).

Make sure that an appropriate _from_ parameter is set.
### Scenario 2: Distribution test

**Test revocation distribution over time**
1. Load _n_ revocations in Cassandra. `revoked_at` will be distributed.
2. Get all revocations
3. Assert that the number of retrieved revocations = _n_
- _n_ is fixed
- for distribution, time slicing will be used, from 1 single slice to slices of 8 hours (our bucket size). Here's a handy dandy scribble showing it:
  ![img_20160414_172706606](https://cloud.githubusercontent.com/assets/1788611/14533766/ba8a37c4-0266-11e6-9846-a9867227acfc.jpg)
### Scenario 3

**Execute scenarios 1 and 2 with varying values of `from` in the GET**

**Comment by jeffsantarossa** [comment]
13 million because we're assuming a worse case scenario of 300 logouts (revocations) / minute. So we have 300 * 60 (min) * 24 (hours) * 30 (days) = ~ 13 million. When we spin up a new token info, it will have to get all of those revocations.

**Comment by jeffsantarossa** [comment]
There's an issue when trying to select between multiple buckets. A select between two buckets seems to work, but once there are more than that, only two buckets are returned. 

See the attached for an example of the database entries and the GET calls.
[revocation-db-buckets.txt](https://github.com/zalando/planb-revocation/files/221169/revocation-db-buckets.txt)

**Comment by LappleApple** [comment]
Hey @gargravarr, this issue dates back to April 2016. Can we close it?

**Comment by gargravarr** [comment]
Close it.
