### ISSUE TITLE
Return 4XX when client token is not JWT

### ISSUE THREAD

**Issue by vroldanbet** [zalando/planb-revocation#104]
RevocationAuthorization needs claim information of the client token, which is not available if token is non JWT. Disallow non JWT claim-based revocation

**Comment by jbellmann** [comment]
@vroldanbet both exceptions are thrown when a controller-method was invoked, so I would do the following, create custom-exceptions for both 'JwtTokenExpectedException' in case of ParseException maybe, and 'AccessTokenExpectedException' in case of 'access_token' not found in SecurityContext, then create and 'ControllerAdvice' for handling these special cases.

**Comment by jbellmann** [comment]
I will implement that in an branch, so you can have a look.

**Comment by vroldanbet** [comment]
Available in master
