### ISSUE TITLE
500 is returned when client token is not valid

### ISSUE THREAD

**Issue by vroldanbet** [zalando/planb-revocation#106]
When the token is invalid, revocation should instead respond 401-

**Comment by gargravarr** [comment]
@vroldanbet checkout this test: https://github.com/zalando/planb-revocation/blob/master/src/test/java/org/zalando/planb/revocation/api/RevocationResourceIT.java#L232

Can you provide more information?

**Comment by vroldanbet** [comment]
The issue relies on stups-spring-oauth2-server library. It does not handle "invalid_token" (401) case, only "invalid_request" (400) 1.0.14.

**Comment by vroldanbet** [comment]
See https://github.com/zalando-stups/stups-spring-oauth2-support/pull/35
