### ISSUE TITLE
Modify "CLAIM" revocation type to match multiple claims

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-revocation#63]
We need to extend the `CLAIM` revocation type to allow matching multiple claim fields:

Post data (POST /revocations):
```json
{
  "claims": {"realm": "/services", "sub": "123"}
}
```

Return value (GET /revocations), "names" are sorted lexicographically:
```json
{
  "names": ["realm", "sub"], 
  "values_hash": "...."
}
```

This is required to match usernames which might not be unique globally (i.e. we need to match realm too).

**Comment by hjacobs** [comment]
The hashing process would be:

* collect values for all given claim names (e.g. "realm" and "sub")
* concatenate these values in the same order as the claim names and separate them with "|"
* hash this string with the configured algorithm (SHA-256 by default) and salt

**Comment by gargravarr** [comment]
Last push also fixe #60 and #56

**Comment by gargravarr** [comment]
Important since the structure of claim revocations changed, Cassandra Test needs to be cleaned up.
