### ISSUE TITLE
Add 'issued_before' to Token Revocation Type

### ISSUE THREAD

**Issue by jeffsantarossa** [zalando/planb-revocation#70]
Use 'issued_after' to set when a revocation of type token should be revoked instead of using the 'revoked_at' field. This will also keep the revocation types more consistent with each other (Global and Claim both used a 'issued_before' field instead of 'revoked_at')

{ "type": "TOKEN", "revoked_at": "1458731586", 
"data": {"token":"J.W.T", "issued_before": "1458731422"} 
}

**Comment by jeffsantarossa** [comment]
See #71 for why 'issued_after' should be added.

**Comment by hjacobs** [comment]
The "IssuedBefore" field should be filled with the current timestamp if not given via REST API (for convenience).

This should work and set issued_before to current time:

```
$ tok=... # some valid token accepted by the configured TOKENINFO_URL
$ curl -X POST \
         -H "Authorization: Bearer $tok" \
         -H 'Content-Type: application/json' \
         -d '{"type": "CLAIM", "data": {"claims": {"sub": "jdoe"}}}' \
         "https://planb-revocation.example.org/revocations"

**Comment by gargravarr** [comment]
@hjacobs referenced also in #81

**Comment by gargravarr** [comment]
#81 included this feature
