### ISSUE TITLE
Don't allow 'revoked_at' in POST

### ISSUE THREAD

**Issue by jeffsantarossa** [zalando/planb-revocation#71]
'revoked_at' is used for getting deltas (i.e. from=... in GET). If users are allowed to set the 'revoked_at' field, the revocation might not be picked up in the next GET. As an example (with easy timestamps):

```
t = 110: POST: revoked_at = 100
t = 115: GET: from = 90 (Picks up the previous POST)
t = 120: GET: from = 115 (No new revocations)
.
.
.
t = 135: GET: from = 115 (No new revocations)
.
.
.
t = 150: POST: revoked_at = 90 (Will only be sent if there's a from <= 90).
t = 155: GET: from = 115 (No new revocations)
```

I would suggest the revocation service sets 'revoked_at' when it receives a POST.

**Comment by gargravarr** [comment]
This issue depends on #70

**Comment by gargravarr** [comment]
This means, remove "revoked_at" field from POST calls

**Comment by danieldelhoyo** [comment]
implemented
