### ISSUE TITLE
Disallow Future Revocations

### ISSUE THREAD

**Issue by gargravarr** [zalando/planb-revocation#81]
See https://github.com/zalando/planb-tokeninfo/issues/43

If no value is given, issued_before should be set to the current timestamp.
Also, a threshold parameter in seconds should be implemented, that embraces clock deviations.

**Comment by hjacobs** [comment]
Just to repeat my wish here: "issued_before" should be optional in the REST API to make it more convenient to write cURL commands, i.e. the example request in https://github.com/zalando/planb-revocation/blob/master/README.rst#testing-the-endpoints should work.

**Comment by hjacobs** [comment]
Also "/revocations?from={timestamp}" should never return "null" values for "issued_before" (this is automatically fixed if "issued_before" is filled with "NOW" by default).

**Comment by hjacobs** [comment]
@gargravarr can we get this done today?

**Comment by gargravarr** [comment]
@hjacobs yes after the meeting :)
