### ISSUE TITLE
Authorization for creating CLAIM revocations

### ISSUE THREAD

**Issue by gargravarr** [zalando/planb-revocation#82]
- Create table in Cassandra
- Create interface (read-only) to Cassandra in service
- Create additional check in POST operations to verify if client is authorized to revoke

**Comment by gargravarr** [comment]
@hjacobs @sarnowski @lmineiro @vroldanbet anything missing?

**Comment by hjacobs** [comment]
We should discuss the exact table structure here --- I would propose using a generic claim/value matching to allow multiple use cases:

* allow client X to revoke all tokens issued for client Y
* allow client X to revoke all tokens in realm R (e.g. application X might be allowed to revoke "/services" tokens)
* allow client X to revoke its own service tokens (i.e. match the "sub" claim with the service username)

**Comment by danieldelhoyo** [comment]
@hjacobs should clients be allowed by default to revoke all their own tokens (use case 3)?

**Comment by hjacobs** [comment]
@danieldelhoyo no, I would solve that with the mapping table, too --- we should have a proposal here (Cassandra `CREATE TABLE` with comments).

**Comment by danieldelhoyo** [comment]
@hjacobs first proposal would be:
CREATE TABLE revocation.authorization_rules (
    source_claim_name TEXT,
    source_claim_value TEXT,
    target_claim_name TEXT,
    target_claim_value TEXT,
    PRIMARY KEY(source_claim_name, source_claim_value, target_claim_name, target_claim_value)
);

**Comment by hjacobs** [comment]
To discuss: 

```cql
CREATE TABLE revocation.authorization_rules (
    source_claims Map<TEXT, TEXT>,
    target_claims Map<TEXT, TEXT>,
    PRIMARY KEY(source_claims, target_claims)
);

**Comment by hjacobs** [comment]
To consider: we need to match multiple claims because "uid" (or "sub") is not globally unique, i.e. "sub" and "realm" needs to both match.

**Comment by hjacobs** [comment]
To keep symmetry, also create its own Spring Security expression for creating CLAIM revocations.

**Comment by hjacobs** [comment]
@danieldelhoyo @vroldanbet and @harti2006 agreed upon:

```cql
CREATE TABLE revocation.authorization_rule (
    uuid TIMEUUID,
    required_user_claims Map<TEXT, TEXT>,
    allowed_revocation_claims Map<TEXT, TEXT>,
    created_by TEXT,
    last_modified_by TEXT,
    PRIMARY KEY(uuid)
);

**Comment by vroldanbet** [comment]
Already available in master, see https://github.com/zalando/planb-revocation/pull/94
