### ISSUE TITLE
Authorization for creating GLOBAL revocations

### ISSUE THREAD

**Issue by hjacobs** [zalando/planb-revocation#87]
GLOBAL revocations should have its own Spring security expression. This allows us to disable posting GLOBAL revocations via REST API.

**Comment by gargravarr** [comment]
Since right now the revocation type comes in the body of the request, I suggest including it in the path when POSTing revocations:

```
/revocations/token
/revocations/claim
/revocations/global
```

Then we could use the path in Spring Security expressions ;)
Also for #82

**Comment by hjacobs** [comment]
@harti2006 maybe you can have a look here? Changing the API to include the type in the past might make sense, but it's an API change and not that nice (different revocation types are not stored differently and the `GET` path also has no type in it).

**Comment by danieldelhoyo** [comment]
@hjacobs let's try to process the payload at springsecurity level instead, so we can avoid this api change

**Comment by harti2006** [comment]
I would keep this simple and add a check in the controller method:

```java
if (revocation.getType() == GLOBAL) {
    throw new AccessDeniedException("Permission denied to create global revocations");
}
```

of course AccessDeniedException has to be translated to 403 somehow.

**Comment by gargravarr** [comment]
@harti2006 that can be done in the @ControllerAdvice
